[project]
name = "image-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "kaggle>=1.7.4.5",
    "kagglehub>=0.3.13",
    "patool>=1.15.0",
]
